# frozen_string_literal: true

require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "lib" << "test"
  t.test_files = FileList["test/**/*_test.rb"]
  t.warning = false
end

desc "Build the gem"
task :build do
  sh "gem build mission_control_dashboard.gemspec"
end

desc "Build and install locally"
task install: :build do
  require_relative "lib/mission_control_dashboard/version"
  sh "gem install mission_control_dashboard-#{MissionControlDashboard::VERSION}.gem"
end

desc "Run the dashboard from source without installing"
task :serve do
  ruby "bin/mission_control server"
end

task default: :test
